/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/step1` | `/step1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/step2` | `/step2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/step3` | `/step3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/+not-found` | `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/step1` | `/step1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/step2` | `/step2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/step3` | `/step3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/+not-found` | `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/step1${`?${string}` | `#${string}` | ''}` | `/step1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/step2${`?${string}` | `#${string}` | ''}` | `/step2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/step3${`?${string}` | `#${string}` | ''}` | `/step3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/step1` | `/step1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/step2` | `/step2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/step3` | `/step3`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/+not-found${`?${string}` | `#${string}` | ''}` | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/+not-found` | `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
